### ISSUE TITLE
New expandable Examples making Pages unsearchable

### ISSUE THREAD

**Issue by gitttt54** [Kometa-Team/Kometa#1366]
### What is the improvement or update to the Wiki you wish to see?

I reccognized, that most examples  are now hidden by default and one has to expand them manually to see the content.

I can see a benefit in this: having not too much information on a single page while landing on it. ok.

But IMHO there are serious drawbacks now:

1) One can not use the browsers search function to search text inside unexpanded boxes

2) One can not oversee all the examples in a single check without expanding all examples before

Means, on a page with 10 examples, one has to click on expand 10 times, before it is possible to search through all the page including the examples. 
Same with skimming over the page looking for a good or suitable example.

IMHO this is very inconvenient and not a good workflow.

I haven't found a way to expand all examples at all. If there is such a button, that would help a little bit, 
but I still think, having all examples expanded when you land on a wiki page is more userfriendly (for the very practical reasons 1+2).

Any Ideas or help on this?

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/config/libraries.html#library-name

(This is just a single example, I haven't checked all pages of course...)

**Comment by YozoraXCII** [comment]
Thanks for the feedback - it's greatly appreciated.

Regarding your first point - I did a quick search for "You can remove overlays from a library by adding remove_overlays: true" on the homepage, and the third option was text that is found within an unexpanded box - I think the issue here is that the specific text isn't highlighted by default - this may be a limitation of the sphinx framework.

I personally think that users are more unlikely to read a wall of text - if they are presented with options they're more likely to seek out the one that sounds like what they're looking for?

I'll take the feedback onboard to see if there's anything we can do to address this.

**Comment by gitttt54** [comment]
> > Regarding your first point - I did a quick search for "You can remove overlays from a library by adding remove_overlays: true" on the homepage, and the third option was text that is found within an unexpanded box - I think the issue here is that the specific text isn't highlighted by default - this may be a limitation of the sphinx framework.

I don't know about sphinx framework, I just use firefox as my browser ;-D
So when I search any text inside an unexpanded box, firefox does not find it (it makes a "not found" sound then). If I expand the box, firefox finds (and highlights) the text.


>> I personally think that users are more unlikely to read a wall of text - if they are presented with options they're more likely to seek out the one that sounds like what they're looking for?

My experience with people regarding "finding specific or unspecific informations on a website or e-book" is this:
they use their eyes to search/scroll text, or
they use the find/search options the application offers.

So yes, they seek out by their possibilities, I guess ;-) 
The more complex a search becomes, the less quickly the result comes, if any.

Thank you.
