### ISSUE TITLE
Failure when using mass_imdb_parental_labels: true

### ISSUE THREAD

**Issue by toddsunpark** [Kometa-Team/Kometa#1427]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

In config.yml:
mass_imdb_parental_labels: true
results in failure after updating from 1.18.3.
I pretty much only use PMM to update the parental label tags.  I've verified my very vanilla config.yml works fine in 1.18.3. 

### Relevant Collection/Overlay/Playlist Definition

```yml
mass_imdb_parental_labels: true
```

**Comment by YozoraXCII** [comment]
Can you provide a log of this?

1: Go to your config folder

2: Go into the logs folder

3: Look for meta.log (not meta.1.log etc)

4. Post it here

Thanks

**Comment by YozoraXCII** [comment]
@toddsunpark `true` is no longer a valid option for `mass_imdb_parental_labels`

We have instead made control more granular so that you can choose what levels you want:

https://metamanager.wiki/en/latest/config/operations.html#mass-imdb-parental-labels

`none`, `mild`, `moderate`, `severe` are the availablbe options.
