### ISSUE TITLE
Letterboxd Lists now Error: Failed to establish a new connection: [Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by kingwoftam** [Kometa-Team/Kometa#1560]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

Starting from today - any Collections that use letterboxd_list or letterboxd_list_details result in connection errors - Unknown Error: HTTPSConnectionPool(redacted): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5a85a37150>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

Possibly caused by the Letterboxd API not shifting into private beta - https://letterboxd.com/api-beta/ - looks like you need to apply to get access to this - assuming this is the cause of the new issue.

**Comment by YozoraXCII** [comment]
I have tested on the latest nightly and can confirm that there are issues, although I get a different error than you:

`Unknown Error: HTTPSConnectionPool(redacted): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002147AD373D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |`

When running a `-lr` to get the logs, I did notice that it's trying to connect to this which is not a valid URL:
`Starting new HTTPS connection (1): letterboxd.combeau-travail:443`

full log attached for @meisnate12 
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/12385326/meta.log)

**Comment by jack2game** [comment]
This has nothing to do with Letterboxd API shifting into private beta - it has been in private beta for ages.

A deeper examine of the log will tell you this was caused when the scrip trying to match a Letterboxd movie with its TMDB ID, while requesting the wrong address such as `letterboxd.combeau-travail:443`

https://github.com/meisnate12/Plex-Meta-Manager/blob/ee20ab6b000b74ae34ac14671788bf7c47587cca/modules/letterboxd.py#L113

Just need to change the line above and everything works like a charm.

Old
`tmdb_id = self._tmdb(f"{base_url}{slug}", language)`
New
`tmdb_id = self._tmdb(f"{base_url}/film/{slug}", language)`
