### ISSUE TITLE
Feature Request: automatically add unmanaged tmdb collections to the Metadata file

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#169]
Add unmanaged collections to the Metadata file with a specified template if the corresponding tmdb collection can be found.

**Comment by Data-Monkey** [comment]
I like the idea but would rather have it optional. 
In my setup something creates a collection for every movie that gets added (maybe Radarr does it).
If that collection name is different from the one I defined in PMM it would create a second entry in the config file.
I would not want that.

**Comment by meisnate12** [comment]
Yea this would definitely be an optional you have to turn on if you want to use it

**Comment by spauldhaliwal** [comment]
It would be useful to be able to blacklist certain collections after they show up. I never use Plex's automatic collection feature because I found it would sometimes make weird collections that, personally, I didn't think should exist. So being able to blacklist these collections as they are noticed would be useful I think.

**Comment by meisnate12** [comment]
Created [`tmdb_collections` Library Operation](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Operations-Attributes#tmdb-collections) so am closing this because this is no longer planned.
