### ISSUE TITLE
[Defaults]: actor.yml doesn't include arr template for radarr/sonarr integration

### ISSUE THREAD

**Issue by zybron** [Kometa-Team/Kometa#1970]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager/blob/master/defaults/both/actor.yml

### Version Number

1.21.0

### What branch are you on?

master

### Describe the Bug

I'm attempting to use the collection configuration below to add missing titles to radarr for a specific actor. This doesn't seem to be working. No missing titles are being added to radarr. I believe may be due to the arr section not being included in the templates in actor.yml. If I am mistaken, please advise the correct format for radarr requests for a specific actor in the actor collections.

```
libraries:
  Movies: 
    collection_files:
    - pmm: actor
      template_variables:
        radarr_add_missing_Samuel L. Jackson: true
```

**Comment by chazlarson** [comment]
This default is based on the contents of your plex library.  It cannot add movies to Radarr since by definition everything it sees is already in Plex.  If you want to fill in all of Mr. Jackson's movies you'd need to use a collection based on an external source like an IMDB search.

Several others work the same way; audio languages, countries, directors, etc.  Generally, if the relevant wiki page says something like: "dynamically create collections based on the most popular actors/actresses **in your library**" that means it's looking at only what's already there and therefore there by definition is nothin g to add to radarr.

This is opposed to something like a Universe collection where there's an external list of things in the Harry Potter universe, which might leave some missing things to send to Radarr.

**Comment by zybron** [comment]
I see and thank you for the clarification. I thought it might be pulling data from an external source and matching local library data. I'll close this since that is not the case.
