### ISSUE TITLE
Update Linuxserver Docker Image Details

### ISSUE THREAD

**Issue by thespad** [Kometa-Team/Kometa#1991]
### What is the improvement or update to the Wiki you wish to see?

The information presented is incorrect and out of date, and it would be appreciated if it could be updated.

> Requires absolute paths in the config. /config/Movies.yml, not config/Movies.yml. Because of this most of the examples in the wiki and config repo don't work as-is with lsio. Config files that work outside of docker often fail because of this with an error referring to /run/s6/services/....

This is no longer the case and relative paths will work as expected (although we still show absolute paths in our docs)

> Only has latest version, no develop or nightly. If you want to switch to develop or nightly to try a new feature, they aren't available with LSIO image.

We have image tags for all 3 releases.

> Doesn't support runtime flags, only ENV vars. 

We handle all runtime flags passed to the container (and also environment variables)

> Doesn't do manual runs correctly; they loop over and over. That command in the previous bullet point [which uses KOMETA_RUN to run it right now] will run over and over until you manually kill the container. The same thing using the official image will run once and quit, as expected.

Manual runs will complete and then the container will exit.

> Resets ownership of entire config dir every run. In tests, the ownership of the config dir and its contents was set to 911:911 with each run.

Ownership of /config is set on init based on whatever UID/GID is passed via the PUID/PGID environment variables, which is common across all of our images. The default, if not set, is 911.

### Does the docs page already exist? Please link to it.

https://kometa.wiki/en/latest/kometa/install/images/#linuxserver

**Comment by YozoraXCII** [comment]
Thanks for the info @thespad - we don't track lsio releases and at the time of writing those details were correct.

We will review and update accordingly

**Comment by thespad** [comment]
Thanks.

It's worth noting that we're in the middle of updating to reflect your rebranding; the image at https://github.com/linuxserver/docker-plex-meta-manager will be archived and replaced with: https://github.com/linuxserver/docker-kometa (GHCR makes renaming repos more trouble than it's worth for us).

**Comment by YozoraXCII** [comment]
@thespad can you review this wording? I don't use lsio myself so I'm going off of what you wrote above

## LinuxServer

The first image offered in unRAID for Kometa is the Linuxserver.io image [`linuxserver/kometa`]

This image is different to the official image [kometateam/kometa] in a couple ways that could cause errors for users who follow our installation guides.

One typical error is something like:

```
Path does not exist: /run/s6/services/kometa/config/SOMETHING
```

The result is that the stock config file and a lot of the examples found in the wiki and config repo don't work.

If you use the LSIO image you should be aware of the following.

The LSIO image:

1. Advises and provides examples of absolute paths in the config, for example `/config/Movies.yml` and not `config/Movies.yml`. Because of this most of the examples in the wiki and config repo don't work as-is with lsio. Config files that work outside of docker often fail because of this with an error referring to `/run/s6/services/...`.

2. Resets ownership of entire config dir every run if the user does not specify a PUID/GUID environment variable. If not set, the ownership of the config dir and its contents is set to 911:911 with each run, which can cause a variety of issues.

Generally speaking, we suggest you use the official image instead of lsio. We do not provide support for issues which relate to using third-party images [lsio or other].

**Comment by thespad** [comment]
This should cover it:

## LinuxServer

The first image offered in unRAID for Kometa is the Linuxserver.io image [`linuxserver/kometa`]

This image is different to the official image [`kometateam/kometa`] in a couple ways that could cause issues for users who follow our installation guides.

If you use the LSIO image you should be aware of the following.

The LSIO image:

1. Advises and provides examples of absolute paths in the config, for example `/config/Movies.yml` and not `config/Movies.yml`, however, relative paths should still work as expected.

2. Resets ownership of entire `/config` dir on startup based on the values of the PUID/PGID environment variables. If not set, the ownership of the `/config` dir and its contents is set to 911:911, which can cause permissions issues.

Generally speaking, we suggest you use the official image instead of LSIO. We do not provide support for issues which relate to using third-party images [LSIO or other].

---

<details><summary>Quick context on the path does not exist bit</summary>
<p>

The `Path does not exist: /run/s6/services/kometa/config/SOMETHING` errors were happening because s6 defaults to a working directory of the servicefile that launches the application, which is `/run/service/<servicename>` and so relative paths are relative to that. We fixed the issue by switching the working directory to `/` before invoking kometa, which gives the same behaviour as your official image.

</p>
</details>

**Comment by YozoraXCII** [comment]
> This should cover it:
> 
> ## LinuxServer
> The first image offered in unRAID for Kometa is the Linuxserver.io image [`linuxserver/kometa`]
> 
> This image is different to the official image [`kometateam/kometa`] in a couple ways that could cause issues for users who follow our installation guides.
> 
> If you use the LSIO image you should be aware of the following.
> 
> The LSIO image:
> 
> 1. Advises and provides examples of absolute paths in the config, for example `/config/Movies.yml` and not `config/Movies.yml`, however, relative paths should still work as expected.
> 2. Resets ownership of entire `/config` dir on startup based on the values of the PUID/GUID environment variables. If not set, the ownership of the `/config` dir and its contents is set to 911:911, which can cause permissions issues.
> 
> Generally speaking, we suggest you use the official image instead of LSIO. We do not provide support for issues which relate to using third-party images [LSIO or other].
> 
> Quick context on the path does not exist bit

Thanks - @chazlarson would you mind reviewing the above?

**Comment by chazlarson** [comment]
Seems fine to me.

**Comment by YozoraXCII** [comment]
This has been incorporated into nightly:

https://kometa.wiki/en/nightly/kometa/install/images/#linuxserver

Marking as resolved
