### ISSUE TITLE
Duplicate Collection

### ISSUE THREAD

**Issue by melbasuonyy** [Kometa-Team/Kometa#236]
I'm getting duplicate collection for movie sets one from plex and one from  PMM 

I think it might be better if movie set is already exist in plex library it should override or just add movies to the set to avoid duplicate 
![Capture](https://user-images.githubusercontent.com/29347988/117672099-91052900-b1ba-11eb-95c4-34d3edb70872.PNG)

below is sample from the movie config

templates:
  Collection:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release

  Zoolander:
    template: {name: Collection, collection: 352789}
  Zorro:
    template: {name: Collection, collection: 1657}

Thanks

**Comment by meisnate12** [comment]
its because the new plex movie agent names collections `<collection name> Collection` vs just `<collection name>` PMM is doing exactly what you're telling it to and adding those movies to the collection you specified. You either have to go into Plex and delete the Collections that end with `Collection` or change the PMM Metadata file and add `Collection` to the end of the Collection names like so:

```yaml
Zoolander Collection:
    template: {name: Collection, collection: 352789}
```
