### ISSUE TITLE
IMDB and TMDB collections are not populating with my library

### ISSUE THREAD

**Issue by dan3093** [Kometa-Team/Kometa#28]
The script appears to be finding and mapping my movies with the imdb ids in the cache file, but when the collections search for matches it is saying that my movies were not found.

The collections generated by searching for actors worked fine but the collections searched for by imdb ids are not populating. Hope I am making sense, here is a copy of my log file.

[meta.log.2021-02-12.zip](https://github.com/meisnate12/Plex-Meta-Manager/files/5975336/meta.log.2021-02-12.zip)

**Comment by dan3093** [comment]
Seems to have resolved itself on the second run.

**Comment by meisnate12** [comment]
actually, this does appear to be a bug where items don't get added to collections on the same run they get added to that cache

**Comment by calboi91** [comment]
I wanted to add to this as well. Items that are updated/added to the cache are listed as missing when adding to the collection in the same run, but the subsequent run adds them fine (since the cache is not updated the second time). 

I attached my log file if that helps.
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/5978680/meta.log)
