### ISSUE TITLE
Feature Request: Sorting "The Title" as "Title, The"

### ISSUE THREAD

**Issue by justinxfisher** [Kometa-Team/Kometa#358]
**Is your feature request related to a problem? Please describe.**
I have a template set up for all of my "general" collections with `sort_title` set as `zzzzz_<<collection_name>>` so these are sorted after my Genres (`*001_<<collection_name>>`), Studios (`*002_<<collection_name>>`), Decades (`*003_<<collection_name>>`), etc.

**Describe the solution you'd like**
I'd like to be able to sort collection names like `"The Avengers"` as `"Avengers, The"`even if I'm already using `sort_title` like the above example. I would still like the displayed name in Plex to read as `"The Avengers"`, but it would be listed with the rest of the "A" collections. I'm thinking this could be implemented in the `settings:` portion of `config.yml` as a kind of global setting for all libraries, or on a library-by-library basis in the `libraries:` section.

**Describe alternatives you've considered**
The only thing I've thought of is renaming all my collections where "The" is at the beginning of the collection name.

**Additional context**

**Comment by meisnate12** [comment]
I added `move_collection_prefix` to templates which when given a list or comma seperated string of prefixes that you want moved to the end of the `<<collection_name>>` ie if you have `move_collection_prefix: The` and the collection is called `The Avengers` then `<<collection_name>>` is replaced with `Avengers, The` instead of `The Avengers`.
