### ISSUE TITLE
Feature Request: Combine all plays from the same type into one popular list

### ISSUE THREAD

**Issue by LeendertPlas** [Kometa-Team/Kometa#361]
**Is your feature request related to a problem? Please describe.**
Current;y, the script takes the popular or most watched list from tautulli from the library that the collection belongs to. If you have your content divided into for example normal content and 4K then playing the 4K version will not add it to the most watched collection for the normal library.

**Describe the solution you'd like**
A solution would be to have the option to combine all Movies libraries, so that you have the most watched movies on your server, no matter what library they belong to.

**Describe alternatives you've considered**
An alternative would be to add the movie to the normal list in tautulli but i'm not sure how that would work

**Additional context**
You would combine multiple tautulli lists into one, which should not add much difficulty as it is repeating the loading process of a single library and then combining it into one list.

**Comment by meisnate12** [comment]
this would be very difficult to add with how PMM is programmed

**Comment by snickers2k** [comment]
yeah i guess this is completely off grid for PMM, 
instead plex should finally implement some kind of a proper quality-handling in their UI. 
It completely suxx to be forced to have 4K and 3D and maybe even special-versions seperated in different libraries. 

i thought about adding all of them as a special to the main-library Version, like i saw some people doing it in the plex forum. This way it's displayed as an "extra" next to the trailer. but at least there you can name it 4K or what ever. not great, but again, keep asking plex a proper solution.

**Comment by meisnate12** [comment]
ive decided im not going to add this so I'm going to close this

**Comment by freakshock88** [comment]
I have noticed this bug as well. In my most popular collection an actually popular movie is not showing up at all, because it is both in a 1080p and 4K collection. The most popular collection is supposed to only contain results from 1080p collection. This movie is among the most popular if I check the API output from tautulli, and the tautulli frontend. The tautulli frontend is able to sum up the total amount of plays.
I guess the movie is discarded however because the tautulli API sets the section_id to the 4K collection (maybe because this version was played latest). It is unfortunate that this causes the movie not to be considered as most popular at all (even when there are enough views in the 1080p section).
