### ISSUE TITLE
Feature Request: Add the ability to generate seperate libraries in the same way as collections.

### ISSUE THREAD

**Issue by c4mz** [Kometa-Team/Kometa#419]
Be able to generate seperate libraries like we do with the collections including filters etc.

https://github.com/adamgot/python-plexlibrary

This guy was successful but development has stopped, it's quite problematic and it only supports Trakt lists and imdb charts.

**Comment by meisnate12** [comment]
this isnt a small request like your last one ill be straight idk when im gonna have time to add anything like this and id add pure playlist support before i added this but ill leave it open and maybe will one day get to it. Is there a reason that you want a specific library instead of just a collection?

**Comment by c4mz** [comment]
That's fine mate. Completely understand. It is a big task and there's plenty of more pressing issues to deal with. Seperate libraries allow you to pin to side bar and apply flex filters etc. More of a convenance than anything. Thank you for the reply!

**Comment by bakes82** [comment]
Cant you pin collections to "home" screens.
![image](https://user-images.githubusercontent.com/3197191/142366426-0e62bbbc-3b2d-4cf7-b807-d51c4f0158b2.png)

**Comment by meisnate12** [comment]
I've looked more into this and they basically use symlinks to create a second library in another folder of the items you want. This is not something that will be possible with pmm as it has no access to the file system on the server and that is something I don't plan on changing. I'm going to close this because it's not something that can be implemented at this time.
