### ISSUE TITLE
Feature Request: Support for TmDb watch_region/with_watch_providers

### ISSUE THREAD

**Issue by dennisoderwald** [Kometa-Team/Kometa#430]
It would be really great if the new filters are added.

https://developers.themoviedb.org/3/discover/tv-discover

**Comment by snown** [comment]
Commit linked to this issue (62532535c9d6d6b2d686716614c36e05c78efc0e) does not resolve issue. Remaining/new issues are:

1. All `with_watch_providers` or `without_watch_providers` entries fail, as they are never referenced in the `_tmdb` function of [modules/builder.py](https://github.com/meisnate12/Plex-Meta-Manager/blob/7fac92652c350ae5a49c1ea455d86a243e8571a1/modules/builder.py#L1048)
2. `with_watch_monetization_types` cannot be used without also specifying a `with_watch_providers` entry, due to the requirement for [`with_watch_monetization_types` to also have `watch_region` defined](https://github.com/meisnate12/Plex-Meta-Manager/blob/7fac92652c350ae5a49c1ea455d86a243e8571a1/modules/builder.py#L1031-L1032), which then hits the rule  that [`watch_region` must have `with_watch_providers` defined](https://github.com/meisnate12/Plex-Meta-Manager/blob/7fac92652c350ae5a49c1ea455d86a243e8571a1/modules/builder.py#L1026-L1027).
3. Similar to number 2. `Without_watch_providers` cannot be used because the `watch_region` rule only checks for `with_watch_providers` to be defined.

These issues persist with the latest develop commit - 7fac92652c350ae5a49c1ea455d86a243e8571a1

My suggested fix would be, in [modules/builder.py](https://github.com/meisnate12/Plex-Meta-Manager/blob/7fac92652c350ae5a49c1ea455d86a243e8571a1/modules/builder.py) to change [lines 1026-1030](https://github.com/meisnate12/Plex-Meta-Manager/blob/7fac92652c350ae5a49c1ea455d86a243e8571a1/modules/builder.py#L1026-L1030) to:
```python
elif discover_attr == "watch_region":
    if "with_watch_providers" in dict_data or "without_watch_providers" in dict_data or "with_watch_monetization_types" in dict_data:
        new_dictionary[discover_final] = discover_data
    else:
        raise Failed(f"Collection Error: {method_name} {discover_final} attribute: must be used with either with_watch_providers, without_watch_providers, or with_watch_monetization_types")
```
and to add the following items to the array on [line 1048](https://github.com/meisnate12/Plex-Meta-Manager/blob/7fac92652c350ae5a49c1ea455d86a243e8571a1/modules/builder.py#L1048)
```python
"with_watch_providers", "without_watch_providers"
```

I can make a pull request doing this if you would like. Just let me know.

**Comment by meisnate12** [comment]
ok this one should work lol
