### ISSUE TITLE
Feature Request: plex metadata export

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#468]
export metadata from plex. like posters, create .nfo etc
and import everything back

optional: save inside movie's folders vs pmm-asset-folder

**Describe alternatives you've considered**
https://github.com/ZeroQI/Lambda.bundle
![best-plugins-for-plex-lambda-autoresized41reY](https://user-images.githubusercontent.com/5986024/144126010-b2f9ba04-7e13-49b7-95db-8f9f3b284e77.jpg)
(found that picture online)

problem here is, that lambda is already outdated with both the cancellation of plex-plugins, aswell as the "sandboxed" version of the new Plex-Agent with no additional 3rd-party-agents. 

thanks

**Comment by Sdub76** [comment]
This would be **huge**.  I have a library with a ton of metadata that I manually entered in Plex that I'd like to be able to export as a backup.  As a starting point, how about an option to export metadata in the PMM YAML format, since PMM is already set up to re-import that.  Same goes with scraping custom metadata posters into the pre-defined image asset folder.  Please please please!!

**Comment by pekempy** [comment]
I agree, I've spent a few days trying to find a metadata exporter that just _works_, and exports the metadata to my medias folder. PMM would be the perfect way to do this

**Comment by ahatdude** [comment]
If I may, I'd add another detail to this:

PMM checking each movie/TV in the _metadata.yml_ and cross-checking with TMDB and seeing if it is part of a collection. If it is, automatically filling that out in _collections.yml_ (or whatever you choose) with the collection name, poster, and films inside.

Ideally, it would cross-check other yml files inside the directory to see if they're already there. For example, I have a specific yml for Lord of the Rings and The Hobbit, because they are all encapsulated by "The Middle Earth Collection" which is not present on TMDB. So I wouldn't be interested in PMM adding them to _collections.yml_, since I already took care of that.

Not sure if this was part of the last update in the develop branch, but I just thought I'd throw it out there if this is in any way doable.

Thanks!

**Comment by meisnate12** [comment]
Keep an eye out in the next major release for dynamic collections it'll do what you want

**Comment by Sdub76** [comment]
I don't get how dynamic collections addresses this.  The feature request is to write existing library metadata to some sort of files for backup/reimport.

**Comment by meisnate12** [comment]
That's was a reply to the above user about tmdb collections this feature was closed because I added the metadata_export library operation
