### ISSUE TITLE
Feature Request: New radarr attribute to upgrade existing movies' quality.

### ISSUE THREAD

**Issue by p5-f20w18k** [Kometa-Team/Kometa#497]
**Describe the solution you'd like**
Add new radarr attribute to upgrade quality of movies on a per collection basis.

**Describe alternatives you've considered**
Current alternative is to remove the movies individually from radarr, use the "radarr_quality" in the .yml under each collection, and have the script re-add it to radarr with the desired quality.

**Additional context**
Discussed in the discord that a new attribute like "radarr_up_quality" would do the job. Although radarr's mass editor can handle this itself, people with thousands of movies in seperate collections would have to spend a lot of time checking the boxes for each movie with the risk of missing some.

**Comment by snickers2k** [comment]
+1

**Comment by Californian** [comment]
I looked at the code where `radarr_quality` is used and it doesn't seem too crazy to implement, I might take a stab at it. Is there anything I should be aware of?

Alternately, I'm willing to pay like $20 if there's a system for issue bounties if it's faster for one of the core devs here to implement it since it would take me a while to get familiar with the codebase (well-structured though it may be), plus the back-and-forth time of addressing the things I inevitably forget.

**Comment by Californian** [comment]
I looked at the code where radarr_quality is used and it doesn't seem too crazy to implement, I might take a stab at it. Is there anything I should be aware of?

**Comment by meisnate12** [comment]
First of all im happy to get some help lol second if your comfortable with using it you should hop on to the PMM Discord and we can talk there im much better about responding there

**Comment by meisnate12** [comment]
Added in 1.17.0
