### ISSUE TITLE
Feature Request: Icon for docker image

### ISSUE THREAD

**Issue by almulder** [Kometa-Team/Kometa#524]
For docker images, could you add an icon so when they show there is an icon, instead of the?
![image](https://user-images.githubusercontent.com/5806190/146668892-24ff112d-abf5-4d6f-97d4-bc076e050e9f.png)

Maybe use an icon like this?
https://i.imgur.com/DX7LsFs.png

I have manually set one, but each update it nukes the custom icon.

**Comment by meisnate12** [comment]
I'm working on something but I'm not going to use the plex icon

**Comment by sreknob** [comment]
I put something simple together because I hate the question marks!
I figure what's more meta than meditation?
It's someone levitating and their shadow is a chevron (not the one from Plex, just generically made).

https://i.imgur.com/6gm6Dyl.png

![plex-meta-manager](https://user-images.githubusercontent.com/6324507/149674318-2474a494-4d38-4fe4-bf0a-24edae4a98bb.png)

Happy to send the source SVG if you care for it.

**Comment by Sdub76** [comment]
> For docker images, could you add an icon so when they show there is an icon, instead of the? ![image](https://user-images.githubusercontent.com/5806190/146668892-24ff112d-abf5-4d6f-97d4-bc076e050e9f.png)
> 
> Maybe use an icon like this? https://i.imgur.com/DX7LsFs.png
> 
> I have manually set one, but each update it nukes the custom icon.

I just used meisnate's avatar in the meantime

https://avatars.githubusercontent.com/u/1631064?v=4

**Comment by meisnate12** [comment]
I'm currently using this image for PMM https://metamanager.wiki/en/latest/_static/pmm.png 

Unfortunately, I cannot add a Logo to the docker Image without an expansive paid corporate account, so im going to close this here
