### ISSUE TITLE
Bug: New device notification

### ISSUE THREAD

**Issue by gitthangbaby** [Kometa-Team/Kometa#683]
**Describe the Bug**
the script triggers "New device" Plex notification on every run despite running from the same device:

```
New Device

_User_ used a new device to access _Server_: _Server_ (Linux)
```

**Relevant Collection Config**
N/A

**Plex Meta Manager Info**
- 1.15.1

**Link to logs (required)**
N/A

Workaround:
`plexapi.BASE_HEADERS['X-Plex-Client-Identifier'] = "Plex-Meta-Manager"` before PlexServer() is initialized in plex.py

**Comment by JonnyWong16** [comment]
Setting a common client identifier for _all_ Plex-Meta-Manager users is a security flaw. Two users should never have identical identifiers.

The proper way to handle this is to generate a UUID on the first run and save that to a config for future use.  Even better, request a new token (using OAuth) for PMM using that client identifier instead of manually inputting a token from somewhere else in the config.
