### ISSUE TITLE
[Feature]: Add original_language filter to dynamic_collections

### ISSUE THREAD

**Issue by hbooo** [Kometa-Team/Kometa#754]
### Is your feature request related to a problem? Please elaborate.

I would like to create dynamic_collections based on spoken language in movies and tv shows

### Describe the solution you'd like

Currently country is available for dynamic_collections but covers only movies and I would like to be able to generate collections based on the spoken language for movies and shows collection

### Additional Information

Discord discussion : https://discord.com/channels/822460010649878528/949316725009154059

**Comment by YozoraXCII** [comment]
Just wanted to throw a potential issue with this out there, I think it can be resolved though:

original_language relies on the metadata of the media within the library. Whilst this in itself is not an issue, we have seen that the original_language within the media's info tends to be written in the original language too. As an example of this, French would be written as français and Thai would be written as ไทย. 

This can be resolved by using the `pre_format_override` attribute, but will involve a lot of time and effort for the end user to map every single language to its English counterpart. I think the more ideal approach would be for the original language dynamic collection's template to pre-map all of the language, which reduces the need of the user having to do it.

**Comment by bullmoose20** [comment]
Country, Audio_language, original_language, would be great if the all translated to two-digit language codes to be standard

**Comment by YozoraXCII** [comment]
> Country, Audio_language, original_language, would be great if the all translated to two-digit language codes to be standard

Completely agree with the request to standardize to the two-digit ISO code as much as possible, but my above issue will persist. You will either have collections called "ไทย" and "Français", or collections named "th" and "fr". 

The data from the API needs to be mapped to English variants so that the collection names are understandable. I believe Plex takes these codes and then translates them within the UI so you see "French" and "Thai" as the language tags.
