### ISSUE TITLE
[Bug]: No logging when container is started in detached mode (docker run -d)

### ISSUE THREAD

**Issue by brodybuster** [Kometa-Team/Kometa#788]
### Version Number

1.16.2

### What branch are you on?

master

### Describe the Bug

I prefer to use Portainer to maintain all my containers. When using docker compose OR starting the container in detached mode:

"docker run -d \
  --restart=unless-stopped \
  -v /path/to/config:/config:rw \
  meisnate12/plex-meta-manager"

or

  plex-meta-manager:
    image: meisnate12/plex-meta-manager
    container_name: plex-meta-manager
    environment:
      - TZ=America/New_York
    volumes:
      - /path/to/config:/config:rw
    command: -t 00:00,12:00  
    restart: unless-stopped

the container stops logging, either to the portainer console, or the local log directory in the config folder. The only thing the portainer shows is "No log line matching the '' filter"

### Logs

https://gist.github.com/BrodyBuster/6f91bafe905e39067908e3d06250ce65

**Comment by chazlarson** [comment]
PMM does send output to the docker log in while in detached mode *while it's actively processing metadata actions*.  It doesn't log the "Waiting until next scheduled time" status line to the log, but when it woke up at 3AM to do its thing there would be log output.

Kicking off an immediate run in daemon mode and checking the log:
```
❯ docker run -it -d -v /opt/chaz-pmm/config:/config meisnate12/plex-meta-manager:develop --config config/config.yml --run
5a2e24b23a45bf8572d711d490b2d9f1d46348a78983accc2b03b7b144e4175c
❯ docker logs 5a2e24b23a45bf8572d711d490b2d9f1d46348a78983accc2b03b7b144e4175c
|====================================================================================================|
|                                                                                                    |
|        ____  _             __  __      _          __  __                                           |
|       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
|       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
|       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
|       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
|                                                                            |___/                   |
|     Version: 1.16.1-develop1                                                                       |
|====================================================================================================|
| --config (PMM_CONFIG): config/config.yml                                                           |
| --time (PMM_TIME): 03:00                                                                           |
... etc
```
So, yes, when you initially start it in "scheduled mode" there will be no logs in the console, but after [or while] running according to the schedule you've set there should be both docker console logs and all the log files on disk.

**Comment by brodybuster** [comment]
thank you. I confirmed that it does log when PMM is actively running during the scheduled time

**Comment by aziascreations** [comment]
I'm sorry for the necroposting here, but I think this could help other people in my situation. since I was having the same issue and wanted a solution that would work in a `docker-compose.yml` file.

**Warning: This is a temporary solution for when you want to debug and test out your config without waiting, this should NOT be used in the long term as it WILL cause your instance of plex meta manager to "boot loop" if used improperly !**

In order to run the script directly, you have to override the `ENTRYPOINT` from the Dockerfile with nearly the same command and with the `--run` option tacked onto the end.
You also have to remove the restart condition.

The new command, as of the time of writing, is the following:
`python3 -u plex_meta_manager.py --run`

I had to remove the `/tini -s` call since I was getting some weird errors where tini wasn't detecting the `-s` option.  *(Docker has a bad habbit of doing that with spaces in commands, and I couldn't be bothered)*
And I also added the `-u` option to Python just to make sure I was getting an output in the console if the script was run as a daemon.  *([StackOverflow post on the issue](https://stackoverflow.com/a/29745541/4135541))*

Regarding the restart condition, I removed it to prevent the container from starting over and over again for no good reason, and to just stop once it had done its job.

Here is an example of the final `docker-compose.yml` file:
```yaml
services:
  plex-meta-manager:
    image: meisnate12/plex-meta-manager
    container_name: plex-meta-manager
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ./config:/config
    entrypoint: "python3 -u plex_meta_manager.py --run"
```

Hope this can help someone out there.

**Comment by chazlarson** [comment]
How does this differ from just setting `PMM_RUN = True` in the env variables?

```
services:
  plex-meta-manager:
    image: meisnate12/plex-meta-manager
    container_name: plex-meta-manager
    environment:
      - TZ=Europe/Brussels
      - PMM_RUN=True
    volumes:
      - ./config:/config
```

That container will run immediately when started and quit when done.

**Comment by aziascreations** [comment]
It looks like it does the same thing, except the `PMM_RUN` does it in a nicer way.

I actually didn't see that one variable in the template docker-compose file where those are typically listed and documented, and I was seeing no mentions on ot in the sections where you first launch the script in the doc.

I guess I'll have to retract that previous comment to the issue. 😬

**Comment by chazlarson** [comment]
They're all listed here:

https://metamanager.wiki/en/latest/home/environmental.html
