### ISSUE TITLE
[Feature]: Trakt AUTH PIN in YML Config

### ISSUE THREAD

**Issue by bakes82** [Kometa-Team/Kometa#800]
### Is your feature request related to a problem? Please elaborate.

Trying to auth trakt in docker/unraid is a PITA, why cant the we put the PIN in the config YML like the ID/Secret?
I can clearly see in the log its not authed, it gives me the URL, so I can auth it, update the YML and boom problem fixed.

### Describe the solution you'd like

Ability to set auth PIN via YML entry in config section for trakt.

**Comment by bakes82** [comment]
@meisnate12 the pin auth working great, can you add another param like "EndIfCantAuth" default it to false, but when true it will stop the process.

**Comment by meisnate12** [comment]
i dont plan on adding that. If you need the URL you can just make it [outlined here in step 6](https://metamanager.wiki/en/nightly/config/trakt.html) and then run pmm with the pin no need to run to get the auth url

**Comment by bakes82** [comment]
So if I issue the PR will you accept?

**Comment by chazlarson** [comment]
What's the use case for stopping when trakt auth can't be completed?  With the addition of the PIN entry, when does it come up?

**Comment by bakes82** [comment]
When you deploy dockers with PMM already configured and a base config/collections, they will run it, some lists wont populate and then be like why is xxx list not there, but if we could set the flag in the config to true, it wouldn't run and they would see the error.
Its a minor use case why I said default it to false :)

**Comment by chazlarson** [comment]
The user has to put in their client ID and secret, yes?  Do they just choose to skip the next step in the process?  Or is that part being done on their behalf?

**Comment by bakes82** [comment]
whats the next step? they dont have shell access

**Comment by bakes82** [comment]
they can just edit the config via web/file browser

**Comment by chazlarson** [comment]
[go to the URL in a browser, collect the PIN, enter it in the config](https://metamanager.wiki/en/nightly/config/trakt.html) at the same time as they enter the client ID and secret.

No shell access required.

**Comment by bakes82** [comment]
Yeah I know how to do that ...... but when not all collections use trakt and they run it they will get 5 collections instead of 15 and be like there is an error, wed rather just not have it run it all.

**Comment by chazlarson** [comment]
My experience is that stopping prematurely like that will result in pretty much all of those people saying "Well, this is busted" and coming to the discord to ask why.  Virtually no one will look at the log to see the "I stopped because you need to do the trakt authentication" reason, so I don't see that as any better than the "not all these collections got created" case, except in that it would take less time to get the message.

It seems to me that if this is for some sort of canned setup, it would be better to not use trakt lists at all in that canned setup, instead create some letterboxd or imdb lists specifically for this purpose since they don't require the user to do anything.  When they want to use trakt lists later, the setup is simple.

**Comment by bakes82** [comment]
Sure you go tell all the people who maintain the trakt lists to go use IMDB or whatever one else you decide on works w/out auth.

Right Id rather fail early then wait 45min for the process to run and then be like oh shits missing.  You want to fail late, so the compromise is to let them do both with a toggle lol.

**Comment by chazlarson** [comment]
No, the person who is creating the canned setup creates his own replacements for those trakt lists for use with the canned setup.

Then the canned setup is guaranteed to work without problems, and you don't have to worry about auth or trakt lists going away.

**Comment by bakes82** [comment]
Yeah never going to happen too many processes automate to trakt bud plus they have their own generated ones that are updated daily/weekly, dunno why you are fighting with me about a process.  Just because you dont use it, doesnt mean its not a valid request that would solve issues for others, Im not asking you to change the default way of doing it.    I can fork it and add it, not a huge deal now that I see what was done to add the pin.

If I went on vacation and got to my destination and they are like you need a passport I would think its better you stop me from boarding the plane.  Dont rely on people to read the documentation 99% dont they just press run and then look for an error.

**Comment by chazlarson** [comment]
In my experience people who don't read docs generally don't look for errors either, but it's ultimately meisnate13's call.  It just seems to me to be a solution to a niche problem that is ultimately avoidable by other means.  

The passport analogy is ridiculous.  If someone were to sell me a prepackaged vacation, and they don't know whether or not I have a passport, I would expect that they won't send me somewhere that requires a passport without telling me.

**Comment by bakes82** [comment]
Not having the pin in the config was fixable other ways too, so why fix things that have work arounds.  Thats the argument now?

**Comment by chazlarson** [comment]
Your stated use case is "dockers with PMM already configured and a base config/collections".  In my opinion, making sure that use case works seamlessly is the responsibility of the entity providing the preconfigured solution.  Adding the PIN aids people who have trouble or are unable to run the script in an interactive mode, like appboxes and the like, who also don't have access to any other machine capable of running a python script.

I don't see how this proposed flag benefits anyone other than someone seeking to provide a preconfigured solution.

Say this proposed flag defaults to false.  I'm a new user who copy/pastes some collections that require Trakt, as happens all the time.  I run the script.  Those collections fail.  I look in the log and see that I have to configure Trakt.

In order for this proposed flag to help me, I have to edit the config file, put in my trakt clientID and secret [or not], then flip this "EndIfCantAuth" flag to true and run the script.  At which point I get told immediately that I need to enter a PIN or auth against Trakt.

In order to get in that state, I apparently read the page about where to put my trakt client ID and secret [or what this flag does] in the config, but skipped or ignored the step where I need to put in a PIN or auth against Trakt in favor of flipping a flag that will later on stop the script early to tell me I need to put in a PIN.  

The user has had to edit the config.yml to enable the script to tell them that they edited it incorrectly.

**Comment by meisnate12** [comment]
for starters i dont like a `EndIfCantAuth` flag theres multiple problems i can think of with that. i would look to have a `--requires-trakt` flag that will just fail if trakt auth fails exactly like tmdb does now, but i would also want a similar flag for all auth services if im gonna have it for one (`Tautulli`, `OMDb`, `MdbList`, `AniDB`, `Trakt`, and `MyAnimeList`).

**Comment by meisnate12** [comment]
Another options would be to create a custom PMM docker container with an entrypoint script that checks if a pin exists before running pmm. You can check for the PIN or do whatever in the entrypoint script and in the event something is missing for your preconfigured set of collections you can fail it before even launching PMM.  If everything is in order then launch PMM as usual.

**Comment by bakes82** [comment]
Im down for the required flag, like I said the PIN auth was the main issue, thats resolve.  The required flags would be an extra QOL maybe for your 2.0 release.

**Comment by meisnate12** [comment]
whenever i get to 2.0 pmm will have a gui lol till then ill just keep upping the feature number

**Comment by bakes82** [comment]
@meisnate12 For the PIN auth, trakt ui has a built in authorize button, if you press it it will give you a pin for your api clientid ;) if you want to add it to the doc instead of manually doing it.
![image](https://user-images.githubusercontent.com/3197191/161197304-2342cbfc-e4ed-4c0a-b011-99b57e36b730.png)
