### ISSUE TITLE
[Feature]: Run with TMDB or TVDB Flag

### ISSUE THREAD

**Issue by zhdenny** [Kometa-Team/Kometa#807]
### Is your feature request related to a problem? Please elaborate.

Use Case - Have Radarr/Sonarr post-processing trigger PMM run an update immediately against a newly added Movie/Show...and only that specific Movie/Show as opposed to an extended/full PMM run.

For example, Radarr grabs new Movie --> Post-Process Script triggers PMM to instantly/efficiently update the Poster Overlay accordingly and skip looking at other Movies/Shows.

### Describe the solution you'd like

Requesting a Run Flag to initiate PMM run against a single Movie/Show via its TMDB or TVDB number.

This would allow PMM to run in a very fine-targeted fashion.

**Comment by chazlarson** [comment]
PMM has to know where to find that movie, and you probably don't want it to run against all instances in all libraries.  For example, My Plex server has six versions of Avengers: Endgame.  That movie appears in a variety of collections across all those libraries.  It may be in playlists.

If PMM gets a request to act on 299534, it's not clear how it would know which libraries, collections, playlists, and/or metadata updates are required without running through them all and looking for TMDB 299534, which doesn't save any time.

**Comment by meisnate12** [comment]
Also pmm doesn't listen for any webhooks or anything on when to run and atm I have no plans of adding that in as a feature.

**Comment by austinwbest** [comment]
> PMM has to know where to find that movie, and you probably don't want it to run against all instances in all libraries. For example, My Plex server has six versions of Avengers: Endgame. That movie appears in a variety of collections across all those libraries. It may be in playlists.
> 
> If PMM gets a request to act on 299534, it's not clear how it would know which libraries, collections, playlists, and/or metadata updates are required without running through them all and looking for TMDB 299534, which doesn't save any time.

Doesn't the cache keep track of that kind of information for better performance? It doesn't seem logical to me that scanning every movie in the entire system would take the same time as a specific one but i dont know the code.. Even if it doesn't cache it, it seems like it would still be faster to loop a list to find matches vs running a full scan of everything



> Also pmm doesn't listen for any webhooks or anything on when to run and atm I have no plans of adding that in as a feature.

Arguments instead of wehooks? `pmm.py --tmdb=12345`

**Comment by chazlarson** [comment]
It caches information about the item:
![image](https://user-images.githubusercontent.com/3865541/160939495-e6cbe636-1b51-4322-aa52-743b5ee0f6b3.png)
but it doesn't cache all the libraries, collections, and playlists that TMDB ID is included in. 

Utilizing Smart Collections as much as one can will get as close as possible to ensuring that when TMDB 299534 shows up in Plex it gets added automatically added to relevant collections like a Marvel collection or the like, but there's no way to know if TMDB 299534 is or would be included in some arbitrary Trakt list, IMDB search, etc. without processing the collection, which means you effectively have to process every collection in every movie library in order to find the ones that TMDB 299534 is part of to update them.

I suppose some minor amount of time might possibly be saved in some situations since PMM wouldn't actually have to create or update all the collections, but it still has process every collection up to the point of having the final list ready to send to Plex to determine whether TMDB 299534 is in there.

**Comment by meisnate12** [comment]
Chaz summed up why this isnt going to be a thing 

> For example, Radarr grabs new Movie --> Post-Process Script triggers PMM to instantly/efficiently update the Poster Overlay accordingly and skip looking at other Movies/Shows.

but what you can do is set up something to just process your overlay collections when a new movie is added it takes a nominal amount of time to check all the overlays tbh i load all the items at once so just set up a pmm run that only runs the overlay collection
