### ISSUE TITLE
[Feature]: trigger search for series being watched

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#822]
### Is your feature request related to a problem? Please elaborate.

sometimes single episodes are missing - which is annoying when already started to watch a series

### Describe the solution you'd like

Would be great to have PMM trigger a sonarr search for a TV-Series being watched right now, to make sure every episode is catched.

**Comment by chazlarson** [comment]
This seems like a duplication of Sonarr's functionality.  You may want to look at [Missarr](https://github.com/l3uddz/missarr) as a way to automate active backlog searches.

**Comment by snickers2k** [comment]
oh, i didn't knew about Missar. Only using Wantarr :D 
thanks.

but is there any way to trigger Missar for a show being watched right now ?
i think the request is still valid, since pmm is also capable of adding missing movies from a collection (also with triggering the search). so would be great to have this for series aswell. especially triggered by actually watching a show.

**Comment by chazlarson** [comment]
That would mean PMM keeping track of everything's watched state, which seems really redundant and leads to a  lot of code defining and maintaining what "currently watching" means and how to track it across multiple users, etc.  If everything is configured correctly, this should be a rare problem, since Sonarr should have picked up the episodes when they showed up on your indexers.  If that didn't happen, it's typically due to the available episodes not hitting a quality threshold, which would still happen if PMM triggered a search, so it feels to me like even if this were implemented it would often  fail to solve the problem it's meant to address.

**Comment by meisnate12** [comment]
This isnt something thats im planning to add because as chaz said most times pmm wouldnt be able to resolve the issue anyways
